steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/wdio-tests', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/wdio-tests' ] # 👈 NECESARIO para que exista en el registro

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'wdio-tests-service', '--image', 'gcr.io/$PROJECT_ID/wdio-tests', '--platform', 'managed', '--region', 'us-central1', '--memory', '1Gi', '--cpu', '1', '--timeout', '900', '--max-instances', '1', '--allow-unauthenticated' ]
images:
- 'gcr.io/$PROJECT_ID/wdio-tests'
